version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
    environment:
      BUILD_DIR: ~/dist
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm run build
            - run:
                name: install AWS CLI
                command: |
                  curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
                  unzip awscliv2.zip
                  sudo ./aws/install
            - deploy:
                name: deploy to AWS
                command: |
                  if [ "${CIRCLE_BRANCH}" = "master" ]; then
                    aws s3 sync $BUILD_DIR s3://antenasclient/ --delete
                  else
                    echo "Not master branch, dry run only"
                  fi
workflows:
    build-and-test:
      jobs:
        - build-and-test
