version: 2.1
orbs:
  node: circleci/node@1.1.6
  aws-s3: circleci/aws-s3@1.0.15
jobs:
  build-and-test:
    executor:
      name: node/default
    environment:
      BUILD_DIR: ./dist/
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run:
                name: Installing dependences
                command: |
                  npm install
            - run: 
                name: Building project
                command: |
                  npm run build
      - aws-s3/sync:
          aws-region: AWS_REGION
          from: dist
          overwrite: true
          to: 's3://antenasclient/'
      - run:
          name: Cleaning Cloudfront's distribution cache
          command: |
            echo "CALMOU TAMO TRABALHANO NISSO AINDA"

workflows:
    build-and-test:
      jobs:
        - build-and-test:
          context: ANTENA
