version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
    environment:
      BUILD_DIR: ./dist/
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run:
                name: Installing dependences
                command: |
                  npm install
            - run: 
                name: Building project
                command: |
                  npm run build
            - run:
                name: Installing AWS CLI
                command: |
                  curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
                  unzip awscliv2.zip
                  sudo ./aws/install
            - deploy:
                name: Deploy to S3
                command: |
                  if [ "${CIRCLE_BRANCH}" = "master" ]; then
                    aws s3 sync $BUILD_DIR s3://antenasclient/ --delete
                  else
                    echo "Not master branch, dry run only"
                  fi
            - run:
                name: Cleaning Cloudfront's distribution cache
                command: |
                  echo "CALMOU TAMO TRABALHANO NISSO AINDA"
workflows:
    build-and-test:
      jobs:
        - build-and-test
